version: '3.8'

networks:
  nyh_network:

services:
  mongo:
    image: mongo:5.0
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: nyh_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - nyh_network

  backend:
    platform: linux/arm64
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/nyh_db
    ports:
      - "8080:8080"
    networks:
      - nyh_network

  frontend:
    platform: linux/arm64
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front
    depends_on:
      - backend
    ports:
      - "4200:80"
      - "80:80"
    networks:
      - nyh_network

volumes:
  mongo-data: